### ISSUE TITLE
make some problem

### ISSUE THREAD

**Issue by xwr96** [JJN123/Fall-Detection#7]
hi! when I run the dae_main_test.py with UR_filled dataset, it casue the error belows. But when I run the thermal dataset, it doesn‘t make a mistake. So can you know what's the problem？ thanks 

>Traceback (most recent call last):
  File "dae_main_test.py", line 22, in <module>
    dae_exp.test(raw = False, animate = True)
  File "/home/rubin/papercode/Fall-Detection-master/ae_exp.py", line 117, in test
    metric = 'AUC', dset = self.dset, raw = raw, animate = animate) #multi_AEmodel.py
  File "/home/rubin/papercode/Fall-Detection-master/multi_AEmodel.py", line 73, in get_stats_for_all_vids
    vid_total = data_dict[Fall_name]['Data'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/rubin/anaconda3/envs/tensorflow/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'Fall1' doesn't exist)"

**Comment by xwr96** [comment]
I had solve it.
Solution:
>delete the .h5 file in the "../H5Data" folder, and rerun again, it will success!
